services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./DB:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  DB: