version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_EXTERNAL_PORT}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - ./DB:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: ${PROD_DATABASE_URL}
      NODE_ENV: production
      PRISMA_CLIENT_OUTPUT_DIR: ${PRISMA_CLIENT_OUTPUT_DIR}
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
    restart: unless-stopped
    entrypoint: /entrypoint.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  DB: